import type { Metadata } from 'next'
import Link from 'next/link'
import { SACRED_CATEGORIES, CATEGORY_GROUPS } from '@/lib/sacred-categories'

const BASE = 'https://sarvdev.com'
const collections = SACRED_CATEGORIES.filter((entry) => entry.isActive)

export const metadata: Metadata = { title: 'Sacred Collections | Sarvdev', description: 'Explore Sarvdev’s sacred temple traditions and pilgrimage collections.', alternates: { canonical: `${BASE}/temples/pilgrimage` } }

export default function PilgrimageIndexPage() {
  const schema = { '@context': 'https://schema.org', '@type': 'CollectionPage', name: 'Sacred Collections', url: `${BASE}/temples/pilgrimage`, mainEntity: { '@type': 'ItemList', itemListElement: collections.map((entry, index) => ({ '@type': 'ListItem', position: index + 1, name: entry.name, url: `${BASE}/temples/pilgrimage/${entry.slug}` })) } }
  return <main className="bg-surface pb-20"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="page-container py-12 sm:py-16"><header className="max-w-3xl border-l-2 border-primary-700 pl-5"><p className="text-overline font-semibold uppercase tracking-[.18em] text-primary-700">Temple traditions</p><h1 className="mt-3 font-serif text-5xl leading-none text-ink sm:text-6xl">Sacred Collections</h1><p className="mt-5 text-lg leading-8 text-ink-muted">Discover project-defined temple traditions, canonical groups and pilgrimage collections. Temple availability is shown on each collection page as Sarvdev records grow.</p></header><div className="mt-14 space-y-14">{CATEGORY_GROUPS.map((group) => { const entries = collections.filter((entry) => entry.group === group.key); return entries.length ? <section key={group.key}><p className="text-overline uppercase tracking-[.16em] text-primary-700">{group.labelHi}</p><h2 className="mt-2 font-serif text-3xl text-ink">{group.label}</h2><div className="mt-6 grid gap-x-10 gap-y-8 md:grid-cols-2">{entries.map((entry, index) => <Link key={entry.slug} href={`/temples/pilgrimage/${entry.slug}`} className={`group border-t border-surface-border pt-4 no-underline ${index % 3 === 0 ? 'md:col-span-2' : ''}`}><p className="text-xs font-semibold uppercase tracking-[.14em] text-primary-700">{entry.deity}</p><h3 className="mt-2 font-serif text-3xl leading-tight text-ink group-hover:text-primary-800">{entry.name}</h3><p className="mt-1 font-devanagari text-base text-ink-muted">{entry.nameHi}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-ink-muted">{entry.description}</p><span className="mt-4 inline-block text-sm text-primary-800 underline">Explore collection</span></Link>)}</div></section> : null })}</div></div></main>
}
