import type { Metadata } from 'next'
import Link from 'next/link'
import { connectDB } from '@/lib/db'
import Darshan from '@/models/Darshan'
import SarvdevImage from '@/components/SarvdevImage'
import { getDarshanCardImage } from '@/lib/media'

export const dynamic = 'force-dynamic'
export const metadata: Metadata = { title: 'Daily Darshan | Sarvdev', description: 'Today’s sacred Darshan from temples across Bharat.' }
type Params = { q?: string; type?: string; temple?: string; deity?: string; state?: string; page?: string }
const TYPES = new Set(['photo', 'video', 'live'])
const escape = (value: string) => value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

export default async function DailyDarshanPage({ searchParams }: { searchParams: Promise<Params> }) {
  const params = await searchParams; const page = Math.max(1, Number(params.page) || 1); const today = new Date().toISOString().slice(0, 10); const filter: any = { status: { $in: ['active', 'approved'] } }
  if (params.type && TYPES.has(params.type)) filter.contentType = params.type
  if (params.temple) filter.templeSlug = params.temple
  if (params.deity) filter.deitySlug = params.deity
  if (params.state) filter.state = new RegExp(escape(params.state), 'i')
  if (params.q) { const q = new RegExp(escape(params.q), 'i'); filter.$or = [{ title: q }, { templeName: q }, { deity: q }, { city: q }, { state: q }] }
  const projection = 'title titleHi slug temple templeName deity city state darshanDate date contentType isLive cardMedia primaryMedia galleryMedia image imageCard thumbnail createdAt'
  let rows: any[] = [], todayRows: any[] = [], total = 0
  try { await connectDB(); [todayRows, rows, total] = await Promise.all([Darshan.find({ ...filter, $or: [{ darshanDate: today }, { date: today }] }).select(projection).sort({ priority: 1, createdAt: -1 }).limit(24).lean(), Darshan.find(filter).select(projection).sort({ darshanDate: -1, date: -1, createdAt: -1 }).skip((page - 1) * 24).limit(24).lean(), Darshan.countDocuments(filter)]) } catch { }
  const todayItems = JSON.parse(JSON.stringify(todayRows)); const items = JSON.parse(JSON.stringify(rows)); const visible = todayItems.length ? todayItems : items; const pages = Math.ceil(total / 24); const schema = [{ '@context': 'https://schema.org', '@type': 'BreadcrumbList', itemListElement: [{ '@type': 'ListItem', position: 1, name: 'Home', item: 'https://sarvdev.com' }, { '@type': 'ListItem', position: 2, name: 'Daily Darshan', item: 'https://sarvdev.com/daily-darshan' }] }, { '@context': 'https://schema.org', '@type': 'ItemList', itemListElement: visible.filter((item: any) => item.slug).map((item: any, index: number) => ({ '@type': 'ListItem', position: index + 1, name: item.title, url: `https://sarvdev.com/daily-darshan/${item.slug}` })) }]
  return <main className="min-h-screen bg-surface pb-20"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><section className="border-b border-surface-border bg-[#f5ede0]"><div className="page-container py-12 sm:py-16"><p className="text-overline font-semibold uppercase tracking-[.16em] text-primary">Today’s Darshan</p><p className="mt-2 font-devanagari text-body text-accent-700">आज के दर्शन</p><h1 className="mt-2 font-display text-h1 text-secondary-800">Daily Darshan</h1><p className="mt-3 max-w-2xl text-body text-ink-muted">Receive today&apos;s sacred Darshan from temples across Bharat.</p></div></section><section className="page-container py-7"><form className="grid gap-3 sm:grid-cols-2 lg:grid-cols-6"><input name="q" defaultValue={params.q} placeholder="Search temples or deities" className="admin-input lg:col-span-2" /><select name="type" defaultValue={params.type || ''} className="admin-input"><option value="">All types</option><option value="photo">Photo</option><option value="video">Video</option><option value="live">Live</option></select><input name="temple" defaultValue={params.temple} placeholder="Temple slug" className="admin-input" /><input name="deity" defaultValue={params.deity} placeholder="Deity slug" className="admin-input" /><button className="btn btn-primary">Find</button></form></section><section className="page-container pb-12"><p className="text-overline font-semibold uppercase tracking-[.14em] text-primary">{todayItems.length ? 'For today' : 'Recent Darshan'}</p><h2 className="mt-2 font-display text-h2 text-secondary-800">{todayItems.length ? 'Today’s Darshan' : 'Recent Darshan'}</h2>{!todayItems.length && <p className="mt-2 text-caption text-ink-muted">No Daily Darshan have been published for today.</p>}{visible.length ? <div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">{visible.map((item: any) => <Card key={String(item._id)} item={item} />)}</div> : <div className="mt-7 border border-surface-border bg-surface-raised p-8 text-ink-muted">No Daily Darshan have been published yet.</div>}{pages > 1 && <nav className="mt-8 flex justify-between"><Link href={page > 1 ? `/daily-darshan?page=${page - 1}` : '#'} className={page > 1 ? 'btn btn-outline' : 'invisible'}>Previous</Link><span className="text-caption text-ink-muted">Page {page} of {pages}</span><Link href={page < pages ? `/daily-darshan?page=${page + 1}` : '#'} className={page < pages ? 'btn btn-outline' : 'invisible'}>Next</Link></nav>}</section></main>
}
function Card({ item }: { item: any }) { const hasMedia = Boolean(item.cardMedia || item.primaryMedia || item.galleryMedia?.[0] || item.imageCard || item.image || item.thumbnail); const location = [item.city, item.state].filter(Boolean).join(', '); return <Link href={item.slug ? `/daily-darshan/${item.slug}` : '#'} className="group overflow-hidden border border-surface-border bg-surface-raised no-underline">{hasMedia && <div className="relative aspect-[4/3] bg-surface-sunken"><SarvdevImage image={getDarshanCardImage(item)} alt={item.title} className="absolute inset-0" imgClassName="object-cover" renderMode="auto" /></div>}<div className="p-5"><div className="flex justify-between gap-3 text-overline font-semibold uppercase tracking-[.12em] text-primary"><span>{item.contentType === 'live' && item.isLive ? 'Live' : item.contentType || 'Photo'}</span>{item.contentType === 'photo' && item.galleryMedia?.length > 1 && <span>{item.galleryMedia.length} photos</span>}</div><h3 className="mt-2 font-display text-h3 text-secondary-800">{item.title}</h3>{item.titleHi && <p className="mt-1 font-devanagari text-caption text-ink-muted">{item.titleHi}</p>}{(item.templeName || item.temple) && <p className="mt-3 text-caption font-semibold text-ink-muted">{item.templeName || item.temple}</p>}{item.deity && <p className="mt-1 text-caption text-ink-muted">{item.deity}{location ? ` · ${location}` : ''}</p>}</div></Link> }
