import type { Metadata } from 'next'
import Link from 'next/link'
import { connectDB } from '@/lib/db'
import SpiritualIcon from '@/models/SpiritualIcon'
import SarvdevImage from '@/components/SarvdevImage'
import { getSpiritualIconCardImage } from '@/lib/temple-image'
import { publicContentSlugFilter } from '@/lib/public-content'

const BASE = 'https://sarvdev.com'; const PAGE_SIZE = 24
export const metadata: Metadata = { title: 'Spiritual Icons of Bharat — Sarvdev', description: 'A growing cultural archive of spiritual personalities represented on Sarvdev.', alternates: { canonical: `${BASE}/spiritual-icons` } }
const projection = 'name nameHi slug category categorySlug title titleHi shortBio primaryMedia cardMedia image imageCard state city priority'

export default async function SpiritualIconsPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string; state?: string; page?: string }> }) {
  const { q = '', category = '', state = '', page: pageValue = '1' } = await searchParams; const page = Math.max(1, Number(pageValue) || 1)
  const filter: Record<string, unknown> = { status: 'active', ...publicContentSlugFilter }; if (category) filter.categorySlug = category; if (state) filter.state = state; if (q.trim()) filter.$or = ['name', 'nameHi', 'title', 'shortBio'].map(field => ({ [field]: { $regex: q.trim(), $options: 'i' } }))
  let items: any[] = []; let total = 0
  try { await connectDB(); [items, total] = await Promise.all([SpiritualIcon.find(filter, projection).sort({ featured: -1, priority: 1, name: 1, _id: 1 }).skip((page - 1) * PAGE_SIZE).limit(PAGE_SIZE).lean(), SpiritualIcon.countDocuments(filter)]) } catch { items = []; total = 0 }
  const pages = Math.max(1, Math.ceil(total / PAGE_SIZE)); const params = (next: number) => { const query = new URLSearchParams(); if (q) query.set('q', q); if (category) query.set('category', category); if (state) query.set('state', state); if (next > 1) query.set('page', String(next)); return `/spiritual-icons${query.size ? `?${query}` : ''}` }
  const jsonLd = { '@context': 'https://schema.org', '@type': 'ItemList', itemListElement: items.map((item, index) => ({ '@type': 'ListItem', position: (page - 1) * PAGE_SIZE + index + 1, name: item.name, url: `${BASE}/spiritual-icons/${item.slug}` })) }
  return <main className="bg-surface pb-20"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} /><div className="page-container py-12 sm:py-16"><header className="max-w-3xl border-l-2 border-primary-700 pl-5"><p className="text-overline uppercase tracking-[.16em] text-primary-700">Cultural archive</p><h1 className="mt-3 font-serif text-4xl text-ink sm:text-5xl">Spiritual Icons of Bharat</h1><p className="mt-5 text-lg leading-8 text-ink-muted">A growing record of spiritual personalities represented through Sarvdev’s managed collection.</p></header><form className="mt-12 grid gap-3 border-y border-surface-border py-5 sm:grid-cols-[1fr_12rem_12rem_auto]"><input name="q" defaultValue={q} className="input" placeholder="Search names or profiles" /><input name="category" defaultValue={category} className="input" placeholder="Category" /><input name="state" defaultValue={state} className="input" placeholder="State" /><button className="btn btn-primary">Search</button></form>{items.length ? <><div className="mt-10 grid gap-x-10 gap-y-9 sm:grid-cols-2 lg:grid-cols-3">{items.map(item => <ProfileCard key={item.slug} item={item} />)}</div>{pages > 1 && <nav className="mt-12 flex justify-between border-t border-surface-border pt-5 text-sm"><span className="text-ink-muted">Page {page} of {pages}</span><span className="flex gap-5">{page > 1 && <Link href={params(page - 1)} className="text-primary-800 underline">Previous</Link>}{page < pages && <Link href={params(page + 1)} className="text-primary-800 underline">Next</Link>}</span></nav>}</> : <section className="mt-12 max-w-2xl border-y border-surface-border py-10"><h2 className="font-serif text-2xl text-ink">No public profiles match this view.</h2><p className="mt-3 text-sm leading-6 text-ink-muted">This archive shows only active records currently available on Sarvdev.</p></section>}</div></main>
}
function ProfileCard({ item }: { item: any }) { const image = getSpiritualIconCardImage(item); return <Link href={`/spiritual-icons/${item.slug}`} className="group border-t border-surface-border pt-4 no-underline"><div className="relative mb-4 aspect-[4/3] overflow-hidden bg-surface-sunken"><SarvdevImage image={image} alt={item.name} className="absolute inset-0" imgClassName="object-cover" /></div><p className="text-xs uppercase tracking-[.14em] text-primary-700">{item.category || item.categorySlug}</p><h2 className="mt-2 font-serif text-2xl text-ink">{item.name}</h2>{item.nameHi && <p className="mt-1 font-devanagari text-ink-muted">{item.nameHi}</p>}{item.title && <p className="mt-2 text-sm text-ink-muted">{item.title}</p>}{item.shortBio && <p className="mt-3 line-clamp-3 text-sm leading-6 text-ink-muted">{item.shortBio}</p>}{[item.city, item.state].filter(Boolean).length > 0 && <p className="mt-3 text-xs text-ink-faint">{[item.city, item.state].filter(Boolean).join(', ')}</p>}</Link> }
