import type { Metadata } from 'next'
import Link from 'next/link'
import SarvdevImage from '@/components/SarvdevImage'
import { getBlogCardImage } from '@/lib/temple-image'
import { formatBlogDate, getBlogExcerpt } from '@/lib/blog-utils'
import { getStoryListing, hasStoryMedia, STORY_PAGE_SIZE } from '@/lib/sacred-stories'

export const metadata: Metadata = { title: 'Sacred Stories | Sarvdev', description: 'Editorial stories connecting temples, deities, pilgrimage, traditions, festivals and devotion.', alternates: { canonical: 'https://sarvdev.com/blog' } }

export default async function BlogPage({ searchParams }: { searchParams: Promise<{ q?: string; category?: string; page?: string }> }) {
  const input = await searchParams; const q = String(input.q || '').trim().slice(0, 120); const category = String(input.category || '').trim().slice(0, 120); const page = Math.max(1, Number(input.page) || 1)
  const { stories, total, categories, pages } = await getStoryListing({ query: q, category, page })
  const href = (p: number) => { const params = new URLSearchParams(); if (q) params.set('q', q); if (category) params.set('category', category); if (p > 1) params.set('page', String(p)); return `/blog${params.size ? `?${params}` : ''}` }
  const itemList = stories.length ? { '@context': 'https://schema.org', '@type': 'ItemList', itemListElement: stories.map((story, index) => ({ '@type': 'ListItem', position: (page - 1) * STORY_PAGE_SIZE + index + 1, name: story.title, url: `https://sarvdev.com/blog/${story.slug}` })) } : null
  return <main className="bg-surface pb-20"><div className="page-container py-12 sm:py-16"><header className="max-w-3xl border-l-2 border-primary-700 pl-5"><p className="text-overline font-semibold uppercase tracking-[.18em] text-primary-700">Sarvdev editorial</p><h1 className="mt-3 font-serif text-5xl leading-none text-ink sm:text-6xl">Sacred Stories</h1><p className="mt-5 text-lg leading-8 text-ink-muted">Temples, deities, festivals, pilgrimage, history and devotion—read with care and context.</p></header>{itemList && <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(itemList) }} />}
    <form action="/blog" className="mt-10 grid gap-3 border-y border-surface-border py-4 sm:grid-cols-[1fr_13rem_auto]"><input name="q" defaultValue={q} placeholder="Search Sacred Stories" className="rounded-btn border border-surface-border bg-white px-4 py-3 text-sm text-ink"/><select name="category" defaultValue={category} className="rounded-btn border border-surface-border bg-white px-3 py-3 text-sm text-ink"><option value="">All subjects</option>{categories.map((entry) => <option key={entry} value={entry}>{entry}</option>)}</select><button className="rounded-btn bg-primary-800 px-5 py-3 text-sm font-semibold text-white">Search</button></form>
    <div className="mt-8 flex justify-between text-sm text-ink-muted"><span>{total ? `${total} ${total === 1 ? 'story' : 'stories'}` : 'No stories yet'}</span>{(q || category) && <Link href="/blog" className="text-primary-800 underline">Clear filters</Link>}</div>
    {stories.length ? <section className="mt-6 grid gap-x-8 gap-y-12 sm:grid-cols-2 lg:grid-cols-3">{stories.map((story) => <article key={String(story._id)} className="border-t border-surface-border pt-4"><Link href={`/blog/${story.slug}`} className="group no-underline">{hasStoryMedia(story) && <div className="relative mb-5 aspect-video overflow-hidden bg-surface-sunken"><SarvdevImage image={getBlogCardImage(story)} alt={story.title} className="absolute inset-0" imgClassName="object-cover transition duration-500 group-hover:scale-[1.03]" /></div>}<div className="flex flex-wrap gap-x-3 text-xs text-ink-muted">{story.category && <span className="font-semibold uppercase tracking-wide text-primary-700">{story.category}</span>}{formatBlogDate(story) && <span>{formatBlogDate(story)}</span>}</div><h2 className="mt-3 font-serif text-3xl leading-tight text-ink group-hover:text-primary-800">{story.title}</h2>{story.titleHi && <p className="mt-1 font-devanagari text-lg text-ink-muted">{story.titleHi}</p>}{getBlogExcerpt(story) && <p className="mt-3 line-clamp-3 text-sm leading-6 text-ink-muted">{getBlogExcerpt(story)}</p>}{story.author && <p className="mt-4 text-xs text-ink-muted">By {story.author}</p>}</Link></article>)}</section> : <section className="mt-10 border-l-2 border-primary-700 bg-surface-sunken p-6"><h2 className="font-serif text-2xl text-ink">No Sacred Stories found</h2><p className="mt-2 text-sm text-ink-muted">Try another search or return as new stories are published.</p></section>}
    {pages > 1 && <nav className="mt-14 flex items-center justify-between border-t border-surface-border pt-6 text-sm">{page > 1 ? <Link href={href(page - 1)} className="text-primary-800 underline">Previous</Link> : <span />}<span className="text-ink-muted">Page {page} of {pages}</span>{page < pages ? <Link href={href(page + 1)} className="text-primary-800 underline">Next</Link> : <span />}</nav>}</div></main>
}
