import Link from 'next/link'
import SarvdevImage from '@/components/SarvdevImage'
import { getTempleCardImage } from '@/lib/temple-image'
import { sanitizeImageUrl } from '@/lib/imageGuard'
import { resolveMediaOriginal, type SarvdevMediaInput } from '@/lib/media-asset'

type Event = { _id?: string; title: string; titleHi?: string; slug?: string; description?: string; shortDescription?: string; startDate?: string; date?: string; endDate?: string; festivalName?: string; deityName?: string; templeName?: string; temple?: string; location?: string; city?: string; state?: string; image?: string; imageCard?: string; imageHero?: string; primaryMedia?: any; cardMedia?: any; heroMedia?: any }

export default function FestivalHorizon({ events }: { events: Event[] }) {
  if (!events.length) return null
  const [featured, ...upcoming] = events
  const featuredHasMedia = hasUsableEventMedia(featured)
  return <section className="bg-surface py-section-sm sm:py-section"><div className="page-container"><div className="flex items-end justify-between gap-5"><div className="max-w-2xl"><p className="text-overline font-semibold uppercase tracking-[.14em] text-primary">Sacred calendar</p><h2 className="mt-2 font-display text-h1 text-secondary-800">Festival Horizon</h2><p className="mt-3 text-body text-ink-muted">Observe what is approaching, and find the places and traditions that hold it.</p></div><Link href="/events" className="hidden text-body-sm font-semibold text-primary-700 no-underline hover:text-maroon sm:inline-flex">View calendar <Arrow /></Link></div>
    <div className="mt-9 grid gap-5 lg:grid-cols-[minmax(0,1.15fr)_minmax(20rem,.85fr)] lg:gap-8"><Link href={`/events/${featured.slug}`} className={`group overflow-hidden border border-surface-border bg-surface-raised no-underline ${featuredHasMedia ? 'grid sm:grid-cols-[.78fr_1.22fr]' : 'block'}`}>{featuredHasMedia && <div className="relative aspect-[4/3] overflow-hidden bg-surface-sunken sm:aspect-auto"><SarvdevImage image={getTempleCardImage(featured)} alt={featured.title} className="absolute inset-0" imgClassName="object-cover transition-transform duration-500 group-hover:scale-[1.02]" renderMode="auto" /></div>}<div className={`${featuredHasMedia ? 'p-6 sm:p-8' : 'p-7 sm:p-9'}`}><DateLabel event={featured} /><h3 className="mt-4 font-display text-[2rem] leading-tight text-secondary-800 group-hover:text-primary-700">{featured.title}</h3>{featured.titleHi && <p className="mt-2 font-devanagari text-body text-ink-muted">{featured.titleHi}</p>}{(featured.shortDescription || featured.description) && <p className="mt-4 text-body-sm leading-6 text-ink-muted line-clamp-3">{featured.shortDescription || featured.description}</p>}<EventMeta event={featured} /><span className="mt-6 inline-flex text-body-sm font-semibold text-primary-700">Explore observance <Arrow /></span></div></Link>
      <div className="divide-y divide-surface-border border-y border-surface-border">{upcoming.map((event) => <Link key={String(event._id || event.slug || event.title)} href={`/events/${event.slug}`} className="group grid grid-cols-[5rem_minmax(0,1fr)] gap-4 py-5 no-underline"><DateLabel event={event} compact /><div><h3 className="font-display text-h4 text-secondary-800 group-hover:text-primary-700">{event.title}</h3><EventMeta event={event} compact /></div></Link>)}</div></div><Link href="/events" className="mt-7 inline-flex text-body-sm font-semibold text-primary-700 no-underline hover:text-maroon sm:hidden">View calendar <Arrow /></Link></div></section>
}
function hasUsableEventMedia(event: Event) { return [event.heroMedia, event.primaryMedia, event.cardMedia, event.imageHero, event.image, event.imageCard].some((media) => Boolean(sanitizeImageUrl(resolveMediaOriginal(media as SarvdevMediaInput), ''))) }
function DateLabel({ event, compact }: { event: Event; compact?: boolean }) { const raw = event.startDate || event.date; if (!raw) return null; const date = new Date(`${raw}T00:00:00`); if (Number.isNaN(date.getTime())) return null; return <p className={`${compact ? 'text-caption leading-5' : 'text-overline tracking-[.14em]'} font-semibold uppercase text-accent-700`}>{compact ? date.toLocaleDateString('en-IN',{day:'2-digit',month:'short'}) : date.toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric'})}</p> }
function EventMeta({ event, compact }: { event: Event; compact?: boolean }) { const location = event.location || [event.city,event.state].filter(Boolean).join(', '); const values=[event.deityName,event.templeName || event.temple,location].filter(Boolean); return values.length ? <p className={`${compact ? 'mt-2' : 'mt-4'} text-caption leading-5 text-ink-muted line-clamp-2`}>{values.join(' · ')}</p> : null }
function Arrow() { return <svg className="ml-1 h-4 w-4" fill="none" stroke="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13.5 4.5 21 12m0 0-7.5 7.5M21 12H3" /></svg> }
