// lib/sacred-categories.ts — Central source of truth for all sacred temple categories
// All pages, forms, and APIs must import from this single file.

export type SacredCategory = {
  slug: string
  name: string          // stored in MongoDB categories/sacredCategories — backward compatible
  nameHi: string
  description: string   // short desc for cards
  longDescription: string // longer desc for pilgrimage pages
  deity: string         // deity tag for UI badge
  icon: string
  group: string         // group key for grouping in UI
  order: number
  isActive: boolean
  relatedSlugs: string[]
}

export type CategoryGroup = {
  key: string
  label: string
  labelHi: string
  order: number
}

export const CATEGORY_GROUPS: CategoryGroup[] = [
  { key: 'shaiva', label: 'Shaiva / Shiva', labelHi: 'शैव / शिव', order: 1 },
  { key: 'shakti', label: 'Shakti / Devi', labelHi: 'शक्ति / देवी', order: 2 },
  { key: 'vaishnav', label: 'Vaishnav / Vishnu / Krishna', labelHi: 'वैष्णव / विष्णु / कृष्ण', order: 3 },
  { key: 'rama', label: 'Rama / Hanuman', labelHi: 'राम / हनुमान', order: 4 },
  { key: 'ganesha', label: 'Ganesha / Murugan', labelHi: 'गणेश / मुरुगन', order: 5 },
  { key: 'geography', label: 'Sacred Geography', labelHi: 'पवित्र भूगोल', order: 6 },
  { key: 'sampradaya', label: 'Saint / Sampradaya', labelHi: 'संत / संप्रदाय', order: 7 },
  { key: 'blessing', label: 'Special Blessings', labelHi: 'विशेष आशीर्वाद', order: 8 },
  { key: 'historical', label: 'Historical / Architecture', labelHi: 'ऐतिहासिक / वास्तुकला', order: 9 },
  { key: 'unique-deities-avatars', label: 'Unique Deities & Avatars', labelHi: 'विशिष्ट देवता और अवतार', order: 10 },
  { key: 'regional-cultural-nature', label: 'Regional, Cultural & Nature', labelHi: 'क्षेत्रीय, सांस्कृतिक और प्रकृति', order: 11 },
  { key: 'specialized-traditions', label: 'Specialized Groups & Traditions', labelHi: 'विशेष समूह और परंपराएं', order: 12 },
  { key: 'other', label: 'Other', labelHi: 'अन्य', order: 13 },
]

// ─── All Sacred Categories ───────────────────────────────────────────────────
// order field controls sort within group; global sort = group.order * 1000 + order

export const SACRED_CATEGORIES: SacredCategory[] = [
  // ── Shaiva / Shiva ──
  { slug: 'jyotirlinga', name: 'Dwadash Jyotirlinga (12 Jyotirlingas)', nameHi: '12 ज्योतिर्लिंग', description: 'The 12 most sacred Shiva shrines where Lord Shiva appeared as blazing light.', longDescription: 'The 12 Jyotirlingas are the most revered Shiva temples in India. According to the Shiva Purana, these are places where Lord Shiva appeared as a blazing column of light (Jyotirlinga). Pilgrims from across the world visit these sacred shrines to seek blessings and moksha.', deity: 'Shiva', icon: '🕉️', group: 'shaiva', order: 1, isActive: true, relatedSlugs: ['char-dham', 'panch-kedar', 'pancha-bhoota-stalam'] },
  { slug: 'panch-kedar', name: 'Panch Kedar', nameHi: 'पंच केदार', description: 'Five sacred Shiva temples in the Garhwal Himalayas.', longDescription: 'The Panch Kedar are five Hindu temples dedicated to Lord Shiva in the Garhwal Himalayan region of Uttarakhand. According to the Mahabharata, these temples mark the spots where different parts of Lord Shiva appeared as a bull to the Pandavas.', deity: 'Shiva', icon: '🏔️', group: 'shaiva', order: 2, isActive: true, relatedSlugs: ['chota-char-dham', 'jyotirlinga', 'pancha-bhoota-stalam'] },
  { slug: 'pancha-bhoota-stalam', name: 'Pancha Bhoota Stalam', nameHi: 'पंच भूत स्थलम', description: 'Five Shiva temples representing earth, water, fire, air, and space.', longDescription: 'The Pancha Bhoota Stalam are five Shiva temples in South India, each representing one of the five elements of nature — earth, water, fire, air, and space. These ancient temples are among the most significant Shaiva shrines.', deity: 'Shiva', icon: '🔥', group: 'shaiva', order: 3, isActive: true, relatedSlugs: ['jyotirlinga', 'panch-kedar', 'divya-desam'] },
  { slug: '108-shiva-temples', name: '108 Shiva Temples', nameHi: '108 शिव मंदिर', description: 'Sacred collection of 108 Shiva temples across India.', longDescription: 'The 108 Shiva temples represent the most significant shrines dedicated to Lord Shiva across the Indian subcontinent. The number 108 holds deep spiritual significance in Hinduism — representing the wholeness of existence.', deity: 'Shiva', icon: '🔱', group: 'shaiva', order: 4, isActive: true, relatedSlugs: ['jyotirlinga', 'panch-kedar', 'pancha-bhoota-stalam'] },
  { slug: 'panch-kailash', name: 'Panch Kailash', nameHi: 'पंच कैलाश', description: 'Five sacred Himalayan Kailash sites — Kailash Mansarovar, Adi Kailash, Kinnaur Kailash, Shrikhand Mahadev and Manimahesh — revered as abodes of Lord Shiva.', longDescription: 'Panch Kailash refers to five sacred Himalayan Kailash sites associated with Lord Shiva: Kailash Mansarovar, Adi Kailash, Kinnaur Kailash, Shrikhand Mahadev Kailash and Manimahesh Kailash. These pilgrimages are revered for their spiritual power, difficult mountain journeys and deep connection with Shiva worship. पंच कैलाश भगवान शिव से जुड़े पाँच पवित्र कैलाश तीर्थों को कहा जाता है — कैलाश मानसरोवर, आदि कैलाश, किन्नौर कैलाश, श्रीखंड महादेव कैलाश और मणिमहेश कैलाश। ये सभी तीर्थ अपनी आध्यात्मिक शक्ति, कठिन हिमालयी यात्राओं और शिव भक्ति के लिए प्रसिद्ध हैं।', deity: 'Shiva', icon: '🏔️', group: 'shaiva', order: 5, isActive: true, relatedSlugs: ['kailash-mansarovar-circuit', 'panch-kedar', 'himalayan-shiva-circuit'] },
  { slug: 'panch-badri', name: 'Panch Badri', nameHi: 'पंच बद्री', description: 'Five sacred temples of Lord Vishnu/Badri in Uttarakhand.', longDescription: 'Panch Badri refers to five sacred Vishnu temples in Uttarakhand associated with the Badri tradition: Badrinath (Vishal Badri), Yogadhyan Badri, Bhavishya Badri, Vridha Badri, and Adi Badri. Together they form one of the most important Vaishnava pilgrimage circuits in the Himalayas.', deity: 'Vishnu', icon: '⛰️', group: 'shaiva', order: 6, isActive: true, relatedSlugs: ['chota-char-dham', 'panch-kedar', 'char-dham'] },
  { slug: 'pancharama-kshetras', name: 'Pancharama Kshetras', nameHi: 'पंचाराम क्षेत्र', description: 'Five ancient Shiva temples in Andhra Pradesh with powerful lingams.', longDescription: 'The Pancharama Kshetras are five ancient Shiva temples located along the banks of river Godavari in Andhra Pradesh. Each temple houses a fragment of a powerful Shiva Lingam said to have been created from the Tarakasura episode.', deity: 'Shiva', icon: '🕉️', group: 'shaiva', order: 7, isActive: true, relatedSlugs: ['jyotirlinga', 'pancha-bhoota-stalam'] },
  { slug: 'pancha-sabhai', name: 'Pancha Sabhai', nameHi: 'पंच सभै', description: 'Five temples where Lord Shiva performed the cosmic dance (Tandava).', longDescription: 'The Pancha Sabhai are five temples in Tamil Nadu where Lord Shiva is believed to have performed the cosmic dance. Each temple represents a different hall or stage (Sabhai) of the divine dance — Kanaka, Rajata, Tamra, Ratna, and Chitra.', deity: 'Shiva', icon: '💃', group: 'shaiva', order: 8, isActive: true, relatedSlugs: ['pancha-bhoota-stalam', 'jyotirlinga'] },
  { slug: 'himalayan-shiva-circuit', name: 'Himalayan Shiva Circuit', nameHi: 'हिमालयन शिव सर्किट', description: 'Sacred Shiva temples across the Himalayan mountain ranges.', longDescription: 'The Himalayan Shiva Circuit covers the most sacred Shiva temples spread across the Himalayan ranges from Kashmir to Arunachal Pradesh. These temples, nestled in breathtaking mountain settings, are among the most spiritually powerful Shiva shrines.', deity: 'Shiva', icon: '🏔️', group: 'shaiva', order: 9, isActive: true, relatedSlugs: ['panch-kedar', 'amarnath-yatra-circuit', 'kailash-mansarovar-circuit'] },
  { slug: 'nandi-temples', name: 'Nandi Temples', nameHi: 'नंदी मंदिर', description: 'Temples dedicated to Nandi, the sacred bull mount of Lord Shiva.', longDescription: 'Nandi temples celebrate the divine bull who serves as the vehicle (vahana) and gatekeeper of Lord Shiva. From the massive Nandi at Lepakshi to the sacred bull at Chamundi Hills, these temples honor Shiva\'s most devoted companion.', deity: 'Shiva', icon: '🐂', group: 'shaiva', order: 10, isActive: true, relatedSlugs: ['jyotirlinga', '108-shiva-temples'] },
  { slug: 'amarnath-yatra-circuit', name: 'Amarnath Yatra Circuit', nameHi: 'अमरनाथ यात्रा सर्किट', description: 'Sacred pilgrimage circuit to the holy Amarnath cave shrine.', longDescription: 'The Amarnath Yatra is one of the holiest Hindu pilgrimages, leading to the Amarnath cave in Jammu & Kashmir where a natural ice Shiva Lingam forms annually. The yatra covers multiple sacred stops and base camps along the traditional route.', deity: 'Shiva', icon: '❄️', group: 'shaiva', order: 11, isActive: true, relatedSlugs: ['himalayan-shiva-circuit', 'kailash-mansarovar-circuit', 'jyotirlinga'] },
  { slug: 'kailash-mansarovar-circuit', name: 'Kailash Mansarovar Circuit', nameHi: 'कैलाश मानसरोवर सर्किट', description: 'The ultimate Shiva pilgrimage to Mount Kailash and Lake Mansarovar.', longDescription: 'The Kailash Mansarovar Yatra is the most sacred pilgrimage for Shaivites, leading to Mount Kailash — believed to be the abode of Lord Shiva — and the pristine Lake Mansarovar in Tibet. This demanding journey is considered the pinnacle of spiritual devotion.', deity: 'Shiva', icon: '🏔️', group: 'shaiva', order: 12, isActive: true, relatedSlugs: ['panch-kailash', 'himalayan-shiva-circuit', 'amarnath-yatra-circuit'] },

  // ── Shakti / Devi ──
  { slug: 'shakti-peeth', name: 'Shakti Peeth (52 Shakti Peethas)', nameHi: '52 शक्ति पीठ', description: 'Sacred Goddess temples where parts of Goddess Sati fell.', longDescription: 'The 52 Shakti Peethas are among the most sacred shrines of the Hindu Goddess tradition. According to legend, when Lord Shiva carried the body of Goddess Sati, Lord Vishnu\'s Sudarshana Chakra cut her body into 52 pieces, each falling at a sacred location.', deity: 'Durga', icon: '🔱', group: 'shakti', order: 1, isActive: true, relatedSlugs: ['18-maha-shakti-peethas', 'nava-durga-temples', 'char-dham'] },
  { slug: '18-maha-shakti-peethas', name: '18 Maha Shakti Peethas', nameHi: '18 महा शक्ति पीठ', description: 'The 18 most powerful Shakti Peethas among all Devi shrines.', longDescription: 'The 18 Maha Shakti Peethas are considered the most powerful among all Shakti Peethas. These temples hold the highest spiritual energy and are revered as the supreme abodes of the Divine Mother across India and neighboring countries.', deity: 'Durga', icon: '🔱', group: 'shakti', order: 2, isActive: true, relatedSlugs: ['shakti-peeth', 'nava-durga-temples', 'siddha-peeths'] },
  { slug: 'nava-durga-temples', name: 'Nava Durga Temples', nameHi: 'नव दुर्गा मंदिर', description: 'Nine temples dedicated to the nine forms of Goddess Durga.', longDescription: 'The Nava Durga temples honor the nine divine forms of Goddess Durga — Shailaputri, Brahmacharini, Chandraghanta, Kushmanda, Skandamata, Katyayani, Kalaratri, Mahagauri, and Siddhidatri. These nine forms are worshipped during Navratri.', deity: 'Durga', icon: '🪷', group: 'shakti', order: 3, isActive: true, relatedSlugs: ['shakti-peeth', 'dasha-mahavidya-temples'] },
  { slug: 'dasha-mahavidya-temples', name: 'Dasha Mahavidya Temples', nameHi: 'दश महाविद्या मंदिर', description: 'Ten temples of the powerful Mahavidya forms of the Goddess.', longDescription: 'The Dasha Mahavidya temples are dedicated to the ten powerful tantric forms of the Divine Mother — Kali, Tara, Tripura Sundari, Bhuvaneshwari, Bhairavi, Chinnamasta, Dhumavati, Bagalamukhi, Matangi, and Kamala. These represent the complete spectrum of feminine divine power.', deity: 'Shakti', icon: '🔥', group: 'shakti', order: 4, isActive: true, relatedSlugs: ['tantra-peethas', 'shakti-peeth', 'nava-durga-temples'] },
  { slug: 'siddha-peeths', name: 'Siddha Peeths', nameHi: 'सिद्ध पीठ', description: 'Sacred seats of spiritual accomplishment and divine feminine power.', longDescription: 'Siddha Peeths are sacred seats where saints and sages attained spiritual accomplishment (siddhi). These powerful shrines of the Goddess tradition are known for granting spiritual powers and fulfilling wishes of devoted pilgrims.', deity: 'Shakti', icon: '✨', group: 'shakti', order: 5, isActive: true, relatedSlugs: ['shakti-peeth', '18-maha-shakti-peethas'] },
  { slug: 'lalita-tripura-sundari-temples', name: 'Lalita Tripura Sundari Temples', nameHi: 'ललिता त्रिपुर सुंदरी मंदिर', description: 'Temples dedicated to Goddess Lalita Tripura Sundari, the supreme beauty.', longDescription: 'Temples dedicated to Goddess Lalita Tripura Sundari, the most beautiful form of the Divine Mother who rules over the three worlds. She is the central deity of the Shri Vidya tradition and represents the supreme beauty of consciousness.', deity: 'Shakti', icon: '🪷', group: 'shakti', order: 6, isActive: true, relatedSlugs: ['dasha-mahavidya-temples', 'shakti-peeth'] },
  { slug: 'tantra-peethas', name: 'Tantra Peethas', nameHi: 'तंत्र पीठ', description: 'Sacred centers of tantric worship and spiritual practices.', longDescription: 'Tantra Peethas are sacred centers where tantric traditions of worship, meditation, and spiritual practice have flourished for centuries. These powerful shrines are associated with esoteric rituals and deep spiritual transformation.', deity: 'Shakti', icon: '🔮', group: 'shakti', order: 7, isActive: true, relatedSlugs: ['dasha-mahavidya-temples', 'siddha-peeths'] },
  { slug: 'himalayan-devi-circuit', name: 'Himalayan Devi Circuit', nameHi: 'हिमालयन देवी सर्किट', description: 'Sacred Goddess temples across the Himalayan mountain ranges.', longDescription: 'The Himalayan Devi Circuit covers the most revered Goddess temples nestled in the Himalayan ranges — from Vaishno Devi in Jammu to Naina Devi, Jwalaji, Chamunda Devi, and Chintpurni. These hill shrines draw millions of devotees annually.', deity: 'Devi', icon: '⛰️', group: 'shakti', order: 8, isActive: true, relatedSlugs: ['shakti-peeth', '18-maha-shakti-peethas', 'himalayan-temples'] },

  // ── Vaishnav / Vishnu / Krishna ──
  { slug: 'divya-desam', name: 'Divya Desam (108 Vishnu Temples)', nameHi: '108 दिव्य देसम', description: '108 sacred Vishnu temples glorified by the Alwar poet-saints.', longDescription: 'The 108 Divya Desams are a group of Hindu Vaishnavite temples glorified in the works of the 12 Alwar poet-saints. Of the 108 temples, 105 are in India, 1 in Nepal, and 2 are considered to be in the celestial realm.', deity: 'Vishnu', icon: '🪷', group: 'vaishnav', order: 1, isActive: true, relatedSlugs: ['pancha-ranga-kshetras', 'nava-tirupati', 'char-dham'] },
  { slug: 'pancha-ranga-kshetras', name: 'Pancha Ranga Kshetras', nameHi: 'पंच रंग क्षेत्र', description: 'Five sacred temples of Lord Ranganatha along the river Kaveri.', longDescription: 'The Pancha Ranga Kshetras are five sacred temples of Lord Ranganatha (reclining Vishnu) located along the banks of river Kaveri in South India. Srirangam, the foremost Divya Desam, is the most prominent among them.', deity: 'Vishnu', icon: '🛕', group: 'vaishnav', order: 2, isActive: true, relatedSlugs: ['divya-desam', 'sleeping-vishnu-temples'] },
  { slug: 'pancha-dwarka', name: 'Pancha Dwarka', nameHi: 'पंच द्वारका', description: 'Five sacred Dwarka temples associated with Lord Krishna.', longDescription: 'The Pancha Dwarka are five sacred sites associated with Lord Krishna\'s kingdom of Dwarka. These temples mark different locations connected to Krishna\'s life in Dwarka and are important pilgrimage destinations for Vaishnavites.', deity: 'Krishna', icon: '🏛️', group: 'vaishnav', order: 3, isActive: true, relatedSlugs: ['krishna-circuit', 'char-dham'] },
  { slug: 'krishna-circuit', name: 'Krishna Circuit', nameHi: 'कृष्ण सर्किट', description: 'Sacred sites associated with Lord Krishna from Mathura to Dwarka.', longDescription: 'The Krishna Circuit traces the divine journey of Lord Krishna from his birthplace Mathura and childhood home Vrindavan, through Gokul, Barsana, to his kingdom in Dwarka. This pilgrimage covers the most sacred Krishna temples across India.', deity: 'Krishna', icon: '🦚', group: 'vaishnav', order: 4, isActive: true, relatedSlugs: ['radha-krishna-temples', 'pancha-dwarka', 'iskcon'] },
  { slug: 'radha-krishna-temples', name: 'Radha Krishna Temples', nameHi: 'राधा कृष्ण मंदिर', description: 'Temples celebrating the divine love of Radha and Krishna.', longDescription: 'Radha Krishna temples celebrate the eternal divine love between Radha and Lord Krishna. From the sacred groves of Vrindavan to temples across India, these shrines honor the most beloved divine couple in Hindu tradition.', deity: 'Krishna', icon: '💕', group: 'vaishnav', order: 5, isActive: true, relatedSlugs: ['krishna-circuit', 'iskcon'] },
  { slug: 'narasimha-temples', name: 'Narasimha Temples', nameHi: 'नरसिंह मंदिर', description: 'Temples dedicated to Lord Narasimha, the fierce avatar of Vishnu.', longDescription: 'Narasimha temples are dedicated to the fierce man-lion avatar of Lord Vishnu, who appeared to protect his devotee Prahlada. These temples are revered for protection and removal of fear and obstacles.', deity: 'Vishnu', icon: '🦁', group: 'vaishnav', order: 6, isActive: true, relatedSlugs: ['divya-desam', 'varaha-kshetras'] },
  { slug: 'kurma-kshetras', name: 'Kurma Kshetras', nameHi: 'कूर्म क्षेत्र', description: 'Sacred sites associated with Lord Vishnu\'s tortoise avatar.', longDescription: 'Kurma Kshetras are sacred sites associated with the Kurma (tortoise) avatar of Lord Vishnu, who supported Mount Mandara during the churning of the cosmic ocean. Sri Kurmam in Andhra Pradesh is the most prominent temple.', deity: 'Vishnu', icon: '🐢', group: 'vaishnav', order: 7, isActive: true, relatedSlugs: ['varaha-kshetras', 'divya-desam'] },
  { slug: 'varaha-kshetras', name: 'Varaha Kshetras', nameHi: 'वराह क्षेत्र', description: 'Temples dedicated to Lord Vishnu\'s boar (Varaha) avatar.', longDescription: 'Varaha Kshetras are sacred temples dedicated to the Varaha (boar) avatar of Lord Vishnu, who rescued the Earth (Bhudevi) from the cosmic ocean. These temples celebrate the divine act of cosmic rescue.', deity: 'Vishnu', icon: '🐗', group: 'vaishnav', order: 8, isActive: true, relatedSlugs: ['kurma-kshetras', 'narasimha-temples', 'divya-desam'] },
  { slug: 'nava-tirupati', name: 'Nava Tirupati', nameHi: 'नव तिरुपति', description: 'Nine sacred Vishnu temples in the Tirunelveli region of Tamil Nadu.', longDescription: 'The Nava Tirupati are nine ancient Vishnu temples located in the Tirunelveli and Thoothukudi districts of Tamil Nadu. Each temple is associated with one of the nine planets (Navagraha) and is glorified in the hymns of the Alwars.', deity: 'Vishnu', icon: '🛕', group: 'vaishnav', order: 9, isActive: true, relatedSlugs: ['divya-desam', 'navagraha'] },
  { slug: 'sleeping-vishnu-temples', name: 'Sleeping Vishnu Temples', nameHi: 'शयन विष्णु मंदिर', description: 'Temples where Lord Vishnu rests in the cosmic sleep (Ananthasayana).', longDescription: 'Sleeping Vishnu temples feature Lord Vishnu in the Ananthasayana (reclining) posture on the cosmic serpent Adi Shesha. From Padmanabhaswamy to the Budhanilkantha in Nepal, these temples showcase the most serene form of the Preserver.', deity: 'Vishnu', icon: '🐍', group: 'vaishnav', order: 10, isActive: true, relatedSlugs: ['pancha-ranga-kshetras', 'divya-desam'] },
  { slug: 'iskcon', name: 'ISKCON Temples', nameHi: 'इस्कॉन मंदिर', description: 'International Krishna Consciousness temples worldwide.', longDescription: 'ISKCON, founded by A.C. Bhaktivedanta Swami Prabhupada in 1966, operates hundreds of temples worldwide dedicated to Lord Krishna. These temples are centers of Bhakti Yoga, Vedic education, and vegetarian prasadam distribution.', deity: 'Krishna', icon: '🪷', group: 'vaishnav', order: 11, isActive: true, relatedSlugs: ['krishna-circuit', 'radha-krishna-temples', 'sapta-puri'] },

  // ── Rama / Hanuman ──
  { slug: 'ramayana-circuit', name: 'Ramayana Circuit', nameHi: 'रामायण सर्किट', description: 'Sacred sites of Lord Ram from Ayodhya to Lanka.', longDescription: 'The Ramayana Circuit covers the sacred sites associated with the life journey of Lord Ram as described in the Ramayana. From his birthplace Ayodhya to Chitrakoot, Panchvati, Hampi (Kishkindha), Rameshwaram, and Sri Lanka — this pilgrimage traces the divine footsteps.', deity: 'Rama', icon: '🏹', group: 'rama', order: 1, isActive: true, relatedSlugs: ['rama-kshetras', 'hanuman-temples', 'char-dham'] },
  { slug: 'hanuman-temples', name: 'Hanuman Temples', nameHi: 'हनुमान मंदिर', description: 'Major temples dedicated to Lord Hanuman across India.', longDescription: 'Hanuman temples celebrate the supreme devotee of Lord Rama, known for his extraordinary strength, courage, and unwavering devotion. From the Sankat Mochan temple in Varanasi to Mehandipur Balaji, these temples are among the most visited in India.', deity: 'Hanuman', icon: '🐒', group: 'rama', order: 2, isActive: true, relatedSlugs: ['panch-mukhi-hanuman-temples', 'ramayana-circuit'] },
  { slug: 'panch-mukhi-hanuman-temples', name: 'Panch Mukhi Hanuman Temples', nameHi: 'पंचमुखी हनुमान मंदिर', description: 'Temples featuring the five-faced form of Lord Hanuman.', longDescription: 'Panch Mukhi (five-faced) Hanuman temples feature the powerful form where Hanuman manifests five faces — Hanuman, Narasimha, Garuda, Varaha, and Hayagriva. This form is revered for supreme protection and removal of all negativity.', deity: 'Hanuman', icon: '🙏', group: 'rama', order: 3, isActive: true, relatedSlugs: ['hanuman-temples', 'ramayana-circuit'] },
  { slug: 'rama-kshetras', name: 'Rama Kshetras', nameHi: 'राम क्षेत्र', description: 'Sacred sites directly associated with Lord Rama\'s life events.', longDescription: 'Rama Kshetras are the holiest sites directly connected to key events in Lord Rama\'s life — his birth in Ayodhya, exile in Chitrakoot, forest years in Panchvati, the bridge at Rameshwaram, and his coronation. Each site is a living monument to the Ramayana.', deity: 'Rama', icon: '🏹', group: 'rama', order: 4, isActive: true, relatedSlugs: ['ramayana-circuit', 'hanuman-temples'] },
  { slug: 'mahabharata-temples', name: 'Mahabharata Temples', nameHi: 'महाभारत मंदिर', description: 'Temples connected to events and characters of the Mahabharata.', longDescription: 'Mahabharata temples are sacred sites connected to the great epic — from Kurukshetra where the Bhagavad Gita was revealed, to Hastinapura, Indraprastha, and numerous temples associated with the Pandavas, Draupadi, and Lord Krishna.', deity: 'Multi', icon: '⚔️', group: 'rama', order: 5, isActive: true, relatedSlugs: ['krishna-circuit', 'panch-kedar'] },

  // ── Ganesha / Murugan ──
  { slug: 'ashta-vinayak', name: 'Ashta Vinayak', nameHi: 'अष्ट विनायक', description: 'Eight ancient Ganesha temples of Maharashtra.', longDescription: 'The Ashta Vinayak are eight ancient Hindu temples of Lord Ganesha in the Indian state of Maharashtra. Each temple has its own unique legend and form of Ganesha, making this one of the most popular pilgrimages in western India.', deity: 'Ganesha', icon: '🐘', group: 'ganesha', order: 1, isActive: true, relatedSlugs: ['21-ganesh-temples', 'siddhivinayak-temples', 'jyotirlinga'] },
  { slug: '21-ganesh-temples', name: '21 Ganesh Temples', nameHi: '21 गणेश मंदिर', description: 'Twenty-one important Ganesha temples across India.', longDescription: 'The 21 Ganesh temples represent the most significant shrines of Lord Ganesha across India, beyond the Ashta Vinayak of Maharashtra. Each temple showcases a unique form of the beloved elephant-headed deity.', deity: 'Ganesha', icon: '🐘', group: 'ganesha', order: 2, isActive: true, relatedSlugs: ['ashta-vinayak', 'siddhivinayak-temples'] },
  { slug: 'siddhivinayak-temples', name: 'Siddhivinayak Temples', nameHi: 'सिद्धिविनायक मंदिर', description: 'Temples dedicated to Siddhivinayak, the wish-fulfilling Ganesha.', longDescription: 'Siddhivinayak temples are dedicated to the wish-fulfilling form of Lord Ganesha. The Siddhivinayak Temple in Mumbai is the most famous, but several other Siddhivinayak shrines across India are known for granting devotees their heartfelt wishes.', deity: 'Ganesha', icon: '✨', group: 'ganesha', order: 3, isActive: true, relatedSlugs: ['ashta-vinayak', '21-ganesh-temples'] },
  { slug: 'arupadai-veedu', name: 'Arupadai Veedu (6 Abodes of Murugan)', nameHi: 'अरुपदै वीडू', description: 'Six abodes of Lord Murugan in Tamil Nadu.', longDescription: 'The Arupadai Veedu (Six Battle Camps) are the six most sacred temples of Lord Murugan in Tamil Nadu. These temples are mentioned in the Sangam Tamil literature and represent the six abodes where Murugan resided after defeating the demon Surapadman.', deity: 'Murugan', icon: '🦚', group: 'ganesha', order: 4, isActive: true, relatedSlugs: ['murugan-hill-temples', 'navagraha', 'divya-desam'] },
  { slug: 'murugan-hill-temples', name: 'Murugan Hill Temples', nameHi: 'मुरुगन पर्वत मंदिर', description: 'Sacred hilltop temples of Lord Murugan (Kartikeya/Subrahmanya).', longDescription: 'Lord Murugan, the divine commander, is traditionally worshipped on hilltops across South India. From Palani and Tiruchendur to Swamimalai and Tiruttani, these hilltop shrines offer breathtaking spiritual experiences.', deity: 'Murugan', icon: '⛰️', group: 'ganesha', order: 5, isActive: true, relatedSlugs: ['arupadai-veedu'] },

  // ── Sacred Geography / Multi-deity ──
  { slug: 'char-dham', name: 'Char Dham', nameHi: 'चार धाम', description: 'Four sacred abodes — Badrinath, Dwarka, Puri, and Rameshwaram.', longDescription: 'Char Dham (four abodes) is the most important Hindu pilgrimage circuit established by Adi Shankaracharya. The four sacred sites — Badrinath (north), Dwarka (west), Puri (east), and Rameshwaram (south) — represent the spiritual corners of India.', deity: 'Multi', icon: '🏔️', group: 'geography', order: 1, isActive: true, relatedSlugs: ['chota-char-dham', 'jyotirlinga', 'sapta-puri'] },
  { slug: 'chota-char-dham', name: 'Chota Char Dham (Uttarakhand)', nameHi: 'छोटा चार धाम', description: 'Yamunotri, Gangotri, Kedarnath, Badrinath — Uttarakhand pilgrimage.', longDescription: 'The Chota Char Dham (Small Four Abodes) is the most popular pilgrimage circuit in the Garhwal Himalayas of Uttarakhand. The four sacred temples — Yamunotri, Gangotri, Kedarnath, and Badrinath — represent the source of India\'s holiest rivers.', deity: 'Multi', icon: '⛰️', group: 'geography', order: 2, isActive: true, relatedSlugs: ['char-dham', 'panch-kedar', 'jyotirlinga'] },
  { slug: 'sapta-puri', name: 'Sapta Puri (7 Sacred Cities)', nameHi: 'सप्त पुरी', description: 'Seven holiest cities that grant moksha.', longDescription: 'The Sapta Puri (Seven Sacred Cities) are the seven most holy cities in Hinduism that are believed to grant moksha (liberation). Each city is associated with specific deities and has immense spiritual significance in Hindu tradition.', deity: 'Multi', icon: '🏛️', group: 'geography', order: 3, isActive: true, relatedSlugs: ['char-dham', 'jyotirlinga', 'shakti-peeth'] },
  { slug: 'panch-prayag', name: 'Panch Prayag', nameHi: 'पंच प्रयाग', description: 'Five sacred river confluences in Uttarakhand.', longDescription: 'The Panch Prayag are five sacred river confluences in the Garhwal region of Uttarakhand where tributaries of the Ganges merge. Each prayag has ancient temples and spiritual significance. Devprayag, where Bhagirathi and Alaknanda merge to form the Ganga, is the most revered.', deity: 'Multi', icon: '🌊', group: 'geography', order: 4, isActive: true, relatedSlugs: ['chota-char-dham', 'panch-kedar', 'sapta-puri'] },
  { slug: 'navagraha', name: 'Navagraha Temples', nameHi: 'नवग्रह मंदिर', description: 'Nine planetary deity shrines for astrological blessings.', longDescription: 'The Navagraha temples are nine Hindu temples, each dedicated to one of the nine major celestial bodies (Navagraha) in Hindu astrology. These temples are primarily located in Tamil Nadu and are believed to have immense spiritual power.', deity: 'Multi', icon: '🌟', group: 'geography', order: 5, isActive: true, relatedSlugs: ['divya-desam', 'pancha-bhoota-stalam'] },
  { slug: 'sapta-ganga', name: 'Sapta Ganga', nameHi: 'सप्त गंगा', description: 'Seven sacred rivers of India personified as goddesses.', longDescription: 'The Sapta Ganga (seven sacred rivers) — Ganga, Yamuna, Godavari, Saraswati, Narmada, Sindhu (Indus), and Kaveri — are personified as goddesses in Hindu tradition. Temples along these rivers hold immense spiritual significance.', deity: 'Multi', icon: '🌊', group: 'geography', order: 6, isActive: true, relatedSlugs: ['sacred-river-temples', 'ganga-origin-circuit', 'panch-prayag'] },
  { slug: 'sacred-river-temples', name: 'Sacred River Temples', nameHi: 'पवित्र नदी मंदिर', description: 'Important temples situated on the banks of sacred rivers.', longDescription: 'Sacred River Temples are temples located along the banks of India\'s holy rivers. From Varanasi on the Ganga to Nasik on the Godavari, these temples have been centers of spirituality and pilgrimage for millennia.', deity: 'Multi', icon: '🏞️', group: 'geography', order: 7, isActive: true, relatedSlugs: ['sapta-ganga', 'temple-ghats'] },
  { slug: 'river-origin-temples', name: 'River Origin Temples', nameHi: 'नदी उद्गम मंदिर', description: 'Temples at the sacred origin points of India\'s great rivers.', longDescription: 'River Origin Temples mark the sacred source points of India\'s great rivers. From Gangotri (Ganga) and Yamunotri (Yamuna) to Trimbakeshwar (Godavari) and Amarkantak (Narmada), these origin sites are among the holiest places.', deity: 'Multi', icon: '⛲', group: 'geography', order: 8, isActive: true, relatedSlugs: ['sapta-ganga', 'ganga-origin-circuit', 'chota-char-dham'] },
  { slug: 'ganga-origin-circuit', name: 'Ganga Origin Circuit', nameHi: 'गंगा उद्गम सर्किट', description: 'The pilgrimage route tracing the origin of the holy Ganga.', longDescription: 'The Ganga Origin Circuit traces the sacred path from Gaumukh glacier (the source of the Bhagirathi) through Gangotri and Devprayag, where it becomes the Ganga. This Himalayan pilgrimage is one of the most spiritually rewarding journeys.', deity: 'Multi', icon: '🏔️', group: 'geography', order: 9, isActive: true, relatedSlugs: ['chota-char-dham', 'river-origin-temples', 'panch-prayag'] },
  { slug: 'temple-ghats', name: 'Temple Ghats', nameHi: 'मंदिर घाट', description: 'Sacred riverfront steps with temples for holy rituals and bathing.', longDescription: 'Temple Ghats are the sacred stepped embankments along holy rivers where devotees perform rituals, take holy dips, and offer prayers. The ghats of Varanasi, Haridwar, Mathura, and Ujjain are among the most spiritually significant in India.', deity: 'Multi', icon: '🛕', group: 'geography', order: 10, isActive: true, relatedSlugs: ['sacred-river-temples', 'sapta-puri'] },
  { slug: 'himalayan-temples', name: 'Himalayan Temples', nameHi: 'हिमालयी मंदिर', description: 'Sacred temples nestled in the mighty Himalayas.', longDescription: 'Himalayan Temples are sacred shrines located across the mighty Himalayan ranges, from Jammu & Kashmir to Arunachal Pradesh. These temples, often in breathtaking mountain settings, are considered to be closest to the heavens.', deity: 'Multi', icon: '🏔️', group: 'geography', order: 11, isActive: true, relatedSlugs: ['himalayan-shiva-circuit', 'himalayan-devi-circuit', 'chota-char-dham'] },
  { slug: 'cave-temples', name: 'Cave Temples', nameHi: 'गुफा मंदिर', description: 'Ancient temples carved into natural caves and rock formations.', longDescription: 'Cave temples are ancient sacred sites carved into natural rock formations. From the Ajanta and Ellora caves to Badami, Elephanta, and Amarnath, these temples showcase incredible artistry and deep spiritual heritage spanning millennia.', deity: 'Multi', icon: '🕳️', group: 'geography', order: 12, isActive: true, relatedSlugs: ['rock-cut-temples', 'unesco-temple-sites'] },
  { slug: 'rock-cut-temples', name: 'Rock Cut Temples', nameHi: 'शैलकर्तित मंदिर', description: 'Magnificent temples hewn from solid rock faces.', longDescription: 'Rock Cut Temples are architectural marvels carved directly from solid rock. From the Kailasa temple at Ellora to the Pancha Rathas at Mahabalipuram, these monuments represent the pinnacle of Indian temple architecture.', deity: 'Multi', icon: '⛏️', group: 'geography', order: 13, isActive: true, relatedSlugs: ['cave-temples', 'unesco-temple-sites', 'ancient-temple-kingdoms'] },
  { slug: 'temple-towns', name: 'Temple Towns', nameHi: 'मंदिर नगर', description: 'Historic towns built around and defined by their great temples.', longDescription: 'Temple Towns are historic settlements that grew around great temples — Madurai, Thanjavur, Kanchipuram, Tirupati, Varanasi, and Puri. These towns continue to be living centers of Hindu worship, culture, and tradition.', deity: 'Multi', icon: '🏘️', group: 'geography', order: 14, isActive: true, relatedSlugs: ['sapta-puri', 'chola-temples', 'kerala-temple-circuit'] },

  // ── Saint / Sampradaya ──
  { slug: 'saptarishi-ashrams', name: 'Saptarishi Ashrams', nameHi: 'सप्तऋषि आश्रम', description: 'Sacred ashrams of the seven great sages (Saptarishi).', longDescription: 'Saptarishi Ashrams are sacred sites associated with the seven great sages — Kashyapa, Atri, Vasishtha, Vishwamitra, Gautama, Jamadagni, and Bharadwaja. These ashrams are revered as seats of ancient Vedic wisdom.', deity: 'Multi', icon: '🧘', group: 'sampradaya', order: 1, isActive: true, relatedSlugs: ['adi-shankaracharya-maths'] },
  { slug: 'adi-shankaracharya-maths', name: 'Adi Shankaracharya Maths', nameHi: 'आदि शंकराचार्य मठ', description: 'Four cardinal monasteries established by Adi Shankaracharya.', longDescription: 'The four Adi Shankaracharya Maths (monasteries) were established by the great philosopher-saint Adi Shankaracharya in the 8th century at Sringeri, Puri, Dwaraka, and Jyotirmath. These are the pillars of the Advaita Vedanta tradition.', deity: 'Multi', icon: '📿', group: 'sampradaya', order: 2, isActive: true, relatedSlugs: ['char-dham', 'sapta-puri'] },
  { slug: 'nath-sampradaya-temples', name: 'Nath Sampradaya Temples', nameHi: 'नाथ संप्रदाय मंदिर', description: 'Temples of the Nath tradition founded by Guru Gorakhnath.', longDescription: 'Nath Sampradaya temples honor the Nath Yogi lineage founded by Guru Gorakhnath. From Gorakhpur to Trimbakeshwar, these temples preserve the tradition of Hatha Yoga, tantra, and the nine Nath saints.', deity: 'Shiva', icon: '🔥', group: 'sampradaya', order: 3, isActive: true, relatedSlugs: ['jyotirlinga', '108-shiva-temples'] },
  { slug: 'jain-tirthas', name: 'Jain Tirthas', nameHi: 'जैन तीर्थ', description: 'Sacred Jain pilgrimage sites and temple complexes.', longDescription: 'Jain Tirthas are the holiest pilgrimage sites of Jainism, including Palitana, Ranakpur, Dilwara, Shravanabelagola, and Parasnath Hill. These magnificent temples are architectural wonders and centers of Jain worship and meditation.', deity: 'Jain', icon: '☸️', group: 'sampradaya', order: 4, isActive: true, relatedSlugs: ['unesco-temple-sites'] },
  { slug: 'buddhist-sacred-circuits', name: 'Buddhist Sacred Circuits', nameHi: 'बौद्ध पवित्र सर्किट', description: 'Sacred Buddhist pilgrimage circuits across India.', longDescription: 'Buddhist Sacred Circuits cover the most important sites in the life of Gautama Buddha — Lumbini (birth), Bodh Gaya (enlightenment), Sarnath (first sermon), and Kushinagar (Mahaparinirvana). These circuits also include Sanchi, Ajanta, and Nalanda.', deity: 'Buddha', icon: '☸️', group: 'sampradaya', order: 5, isActive: true, relatedSlugs: ['unesco-temple-sites', 'cave-temples'] },

  // ── Special Blessings ──
  { slug: 'marriage-blessing-temples', name: 'Marriage Blessing Temples', nameHi: 'विवाह आशीर्वाद मंदिर', description: 'Temples famous for blessings for a happy married life.', longDescription: 'Marriage Blessing Temples are renowned for granting blessings for finding a suitable partner, happy married life, and marital harmony. Devotees visit these sacred shrines to seek divine grace for their matrimonial journey.', deity: 'Multi', icon: '💒', group: 'blessing', order: 1, isActive: true, relatedSlugs: ['child-blessing-temples'] },
  { slug: 'child-blessing-temples', name: 'Child Blessing Temples', nameHi: 'संतान प्राप्ति मंदिर', description: 'Temples known for blessings of children (Santan Prapti).', longDescription: 'Child Blessing Temples are sacred shrines visited by couples seeking the divine blessing of children (Santan Prapti). From Santan Gopala temples to specific shrines of Devi and Shiva, these temples have fulfilled the wishes of countless devotees.', deity: 'Multi', icon: '👶', group: 'blessing', order: 2, isActive: true, relatedSlugs: ['fertility-temples', 'marriage-blessing-temples'] },
  { slug: 'education-temples', name: 'Education Temples', nameHi: 'शिक्षा मंदिर', description: 'Temples dedicated to knowledge, wisdom, and academic success.', longDescription: 'Education Temples are dedicated to deities of knowledge and wisdom — primarily Goddess Saraswati, Lord Hayagriva, and Lord Dakshinamurthy. Students and scholars visit these temples seeking blessings for academic success and wisdom.', deity: 'Saraswati', icon: '📚', group: 'blessing', order: 3, isActive: true, relatedSlugs: ['wealth-prosperity-temples'] },
  { slug: 'wealth-prosperity-temples', name: 'Wealth & Prosperity Temples', nameHi: 'धन और समृद्धि मंदिर', description: 'Temples famous for blessings of wealth and financial prosperity.', longDescription: 'Wealth & Prosperity Temples are dedicated to Goddess Lakshmi, Lord Kubera, and other deities associated with abundance. Devotees visit these temples seeking financial prosperity, business success, and removal of debts.', deity: 'Lakshmi', icon: '💰', group: 'blessing', order: 4, isActive: true, relatedSlugs: ['education-temples'] },
  { slug: 'healing-temples', name: 'Healing Temples', nameHi: 'चिकित्सा मंदिर', description: 'Temples known for healing powers and curing ailments.', longDescription: 'Healing Temples are sacred sites known for their miraculous healing powers. From Lord Dhanvantari temples to specific Shiva and Devi shrines, devotees visit these temples seeking relief from illness and physical afflictions.', deity: 'Multi', icon: '💚', group: 'blessing', order: 5, isActive: true, relatedSlugs: ['protection-temples'] },
  { slug: 'protection-temples', name: 'Protection Temples', nameHi: 'रक्षा मंदिर', description: 'Temples for divine protection from evil and negative forces.', longDescription: 'Protection Temples are powerful shrines known for offering divine protection from evil, negative energies, and spiritual threats. Temples of Hanuman, Bhairava, and Kali are especially revered for their protective powers.', deity: 'Multi', icon: '🛡️', group: 'blessing', order: 6, isActive: true, relatedSlugs: ['black-magic-removal-temples', 'hanuman-temples'] },
  { slug: 'black-magic-removal-temples', name: 'Black Magic Removal Temples', nameHi: 'काला जादू निवारण मंदिर', description: 'Temples renowned for removing black magic and evil eye effects.', longDescription: 'Black Magic Removal Temples are powerful shrines known for their ability to remove effects of black magic, evil eye (Nazar), and negative spiritual influences. Mehandipur Balaji and similar temples are visited by thousands seeking spiritual cleansing.', deity: 'Hanuman', icon: '🔮', group: 'blessing', order: 7, isActive: true, relatedSlugs: ['protection-temples', 'hanuman-temples'] },
  { slug: 'fertility-temples', name: 'Fertility Temples', nameHi: 'प्रजनन मंदिर', description: 'Ancient temples with fertility rites and blessings.', longDescription: 'Fertility Temples are ancient sacred sites associated with fertility rites, prayers for progeny, and celebration of the creative life force. These temples honor the divine masculine and feminine principles of creation.', deity: 'Multi', icon: '🌱', group: 'blessing', order: 8, isActive: true, relatedSlugs: ['child-blessing-temples'] },

  // ── Historical / Architecture ──
  { slug: 'unesco-temple-sites', name: 'UNESCO Temple Sites', nameHi: 'यूनेस्को मंदिर स्थल', description: 'Temple sites recognized as UNESCO World Heritage Sites.', longDescription: 'UNESCO Temple Sites are sacred temples and temple complexes recognized as World Heritage Sites for their outstanding universal value. From Khajuraho and Hampi to Mahabalipuram and the Sun Temple of Konark, these sites are treasures of human civilization.', deity: 'Multi', icon: '🏛️', group: 'historical', order: 1, isActive: true, relatedSlugs: ['chola-temples', 'ancient-temple-kingdoms', 'rock-cut-temples'] },
  { slug: 'chola-temples', name: 'Chola Temples', nameHi: 'चोल मंदिर', description: 'Magnificent temples built by the Chola dynasty in Tamil Nadu.', longDescription: 'Chola Temples are architectural masterpieces built by the mighty Chola dynasty of Tamil Nadu. The Brihadeeswarar Temple in Thanjavur, Gangaikonda Cholapuram, and Airavatesvara Temple are UNESCO World Heritage Sites showcasing the grandeur of Chola architecture.', deity: 'Shiva', icon: '🏛️', group: 'historical', order: 2, isActive: true, relatedSlugs: ['unesco-temple-sites', 'temple-architecture-styles', 'temple-towns'] },
  { slug: 'kerala-temple-circuit', name: 'Kerala Temple Circuit', nameHi: 'केरल मंदिर सर्किट', description: 'Famous temple pilgrimage circuit across God\'s Own Country.', longDescription: 'The Kerala Temple Circuit covers the most revered temples of Kerala — from Guruvayur and Padmanabhaswamy to Sabarimala and Chottanikkara. Kerala\'s unique temple architecture and festivals make this a spiritually enriching pilgrimage.', deity: 'Multi', icon: '🌴', group: 'historical', order: 3, isActive: true, relatedSlugs: ['divya-desam', 'temple-towns'] },
  { slug: 'ancient-temple-kingdoms', name: 'Ancient Temple Kingdoms', nameHi: 'प्राचीन मंदिर राज्य', description: 'Temple complexes from great ancient Indian kingdoms.', longDescription: 'Ancient Temple Kingdoms celebrates the grand temple complexes built by India\'s great dynasties — the Cholas, Pallavas, Chalukyas, Hoysalas, Kakatiyas, and Vijayanagara. Each dynasty left behind architectural masterpieces that define Indian temple art.', deity: 'Multi', icon: '👑', group: 'historical', order: 4, isActive: true, relatedSlugs: ['chola-temples', 'unesco-temple-sites', 'temple-architecture-styles'] },
  { slug: 'temple-architecture-styles', name: 'Temple Architecture Styles', nameHi: 'मंदिर वास्तुकला शैली', description: 'Temples showcasing diverse Indian architectural styles.', longDescription: 'Indian temples exhibit incredible diversity in architecture — from the Nagara style of North India and the Dravidian style of the South to the Vesara, Kalinga, and Kerala styles. This category explores temples that best represent each architectural tradition.', deity: 'Multi', icon: '🏗️', group: 'historical', order: 5, isActive: true, relatedSlugs: ['ancient-temple-kingdoms', 'chola-temples', 'rock-cut-temples'] },

  // ── Unique Deities & Avatars ──
  { slug: 'brahma-temples', name: 'Brahma Temples', nameHi: 'ब्रह्मा मंदिर', description: 'Rare temples dedicated to Lord Brahma, the Creator, such as the famous shrine in Pushkar.', longDescription: 'Brahma Temples are rare sacred shrines dedicated to Lord Brahma, the Creator in the Hindu Trinity. The Pushkar Brahma Temple is the most famous example, while other lesser-known shrines preserve this unique worship tradition.', deity: 'Brahma', icon: '🦢', group: 'unique-deities-avatars', order: 1, isActive: true, relatedSlugs: ['dattatreya-temples', 'harihara-temples'] },
  { slug: 'surya-temples', name: 'Surya Temples', nameHi: 'सूर्य मंदिर', description: 'Architectural marvels dedicated to the Sun God, featuring magnificent solar alignments.', longDescription: 'Surya Temples are architectural marvels dedicated to the Sun God. Many are known for magnificent solar alignments, precise temple geometry, and rituals connected with health, light, vitality, and the cosmic rhythm of time.', deity: 'Surya', icon: '☀️', group: 'unique-deities-avatars', order: 2, isActive: true, relatedSlugs: ['nakshatra-temples', 'rashi-temples'] },
  { slug: 'saraswati-temples', name: 'Saraswati Temples', nameHi: 'सरस्वती मंदिर', description: 'Temples exclusively dedicated to the Goddess of Knowledge, Music, and Arts.', longDescription: 'Saraswati Temples are shrines dedicated to the Goddess of Knowledge, Music, Speech, and Arts. Students, musicians, writers, and seekers of wisdom visit these temples for blessings of learning and creative clarity.', deity: 'Saraswati', icon: '🎼', group: 'unique-deities-avatars', order: 3, isActive: true, relatedSlugs: ['education-temples'] },
  { slug: 'bhairava-temples', name: 'Bhairava Temples', nameHi: 'भैरव मंदिर', description: 'Shrines of Lord Kal Bhairava, the fierce guardian manifestation of Lord Shiva.', longDescription: 'Bhairava Temples are shrines of Lord Kal Bhairava, the fierce guardian manifestation of Lord Shiva. These temples are especially revered for protection, discipline, removal of fear, and sacred guardianship of pilgrimage towns.', deity: 'Shiva', icon: '🐕', group: 'unique-deities-avatars', order: 4, isActive: true, relatedSlugs: ['protection-temples', 'tantra-peethas', '108-shiva-temples'] },
  { slug: 'dattatreya-temples', name: 'Dattatreya Temples', nameHi: 'दत्तात्रेय मंदिर', description: 'Temples dedicated to the combined avatar of the Holy Trinity: Brahma, Vishnu, and Shiva.', longDescription: 'Dattatreya Temples honor Lord Dattatreya, the combined avatar of Brahma, Vishnu, and Shiva. These temples are connected with renunciation, yogic wisdom, saint traditions, and the unity of the Hindu Trinity.', deity: 'Multi', icon: '🧘', group: 'unique-deities-avatars', order: 5, isActive: true, relatedSlugs: ['saptarishi-ashrams', 'adi-shankaracharya-maths'] },
  { slug: 'sapta-matrika-temples', name: 'Sapta Matrika Temples', nameHi: 'सप्त मातृका मंदिर', description: 'Ancient shrines dedicated to the Seven Divine Mothers, the Matrikas of Hindu mythology.', longDescription: 'Sapta Matrika Temples are ancient shrines dedicated to the Seven Divine Mothers of Hindu mythology. These Matrikas represent protective feminine power and are connected with Shakti worship, village guardianship, and tantric traditions.', deity: 'Devi', icon: '🌺', group: 'unique-deities-avatars', order: 6, isActive: true, relatedSlugs: ['shakti-peeth', 'nava-durga-temples', 'sapta-matrika-temples'] },
  { slug: 'dashavatara-temples', name: 'Dashavatara Temples', nameHi: 'दशावतार मंदिर', description: 'Temples honoring all ten principal avatars, Dashavatara, of Lord Vishnu.', longDescription: 'Dashavatara Temples honor the ten principal avatars of Lord Vishnu. These sacred sites celebrate the divine descent of Vishnu across cosmic ages, from Matsya and Kurma to Rama, Krishna, Buddha, and Kalki traditions.', deity: 'Vishnu', icon: '🎭', group: 'unique-deities-avatars', order: 7, isActive: true, relatedSlugs: ['divya-desam', 'pancha-ranga-kshetras', 'krishna-circuit'] },
  { slug: 'ardhanarishvara-temples', name: 'Ardhanarishvara Temples', nameHi: 'अर्धनारीश्वर मंदिर', description: 'Temples worshiping the combined half-male, half-female form of Shiva and Parvati.', longDescription: 'Ardhanarishvara Temples worship the united form of Shiva and Parvati, representing the inseparable balance of masculine and feminine principles. These temples express cosmic unity, harmony, and the completeness of divine consciousness.', deity: 'Shiva', icon: '🌗', group: 'unique-deities-avatars', order: 8, isActive: true, relatedSlugs: ['108-shiva-temples', 'shakti-peeth', 'lalita-tripura-sundari-temples'] },
  { slug: 'harihara-temples', name: 'Harihara Temples', nameHi: 'हरिहर मंदिर', description: 'Sacred shrines dedicated to the fused form of Vishnu, Hari, and Shiva, Hara.', longDescription: 'Harihara Temples are dedicated to the fused form of Vishnu and Shiva, symbolizing the unity of Hari and Hara. These shrines are important examples of devotional harmony between Vaishnava and Shaiva traditions.', deity: 'Multi', icon: '🕉️', group: 'unique-deities-avatars', order: 9, isActive: true, relatedSlugs: ['jyotirlinga', 'divya-desam', 'dattatreya-temples'] },
  { slug: 'garuda-temples', name: 'Garuda Temples', nameHi: 'गरुड़ मंदिर', description: 'Temples dedicated to Garuda, the mighty eagle and sacred mount of Lord Vishnu.', longDescription: 'Garuda Temples honor Garuda, the mighty eagle and sacred mount of Lord Vishnu. These temples are especially associated with devotion, protection, strength, and traditional remedies connected with serpent afflictions.', deity: 'Vishnu', icon: '🦅', group: 'unique-deities-avatars', order: 10, isActive: true, relatedSlugs: ['divya-desam', 'pancha-ranga-kshetras'] },
  { slug: 'ayyappa-temples', name: 'Ayyappa Temples', nameHi: 'अय्यप्पा मंदिर', description: 'Major pilgrimage shrines of Lord Ayyappa, including the sacred Sabarimala circuit.', longDescription: 'Ayyappa Temples are major pilgrimage shrines dedicated to Lord Ayyappa, especially revered in South India. The Sabarimala pilgrimage is the best-known Ayyappa tradition, emphasizing discipline, devotion, austerity, and equality among devotees.', deity: 'Multi', icon: '🐯', group: 'unique-deities-avatars', order: 11, isActive: true, relatedSlugs: ['kerala-temple-circuit', 'himalayan-temples'] },
  { slug: 'naga-devata-temples', name: 'Naga Devata Temples', nameHi: 'नाग देवता मंदिर', description: 'Highly revered temples dedicated to ancient serpent deities and snake worship.', longDescription: 'Naga Devata Temples are highly revered shrines dedicated to ancient serpent deities. These temples are connected with fertility, land protection, ancestral worship, monsoon blessings, and traditional remedies for Naga dosha.', deity: 'Multi', icon: '🐍', group: 'unique-deities-avatars', order: 12, isActive: true, relatedSlugs: ['fertility-temples', 'protection-temples'] },
  { slug: 'sita-mata-temples', name: 'Sita Mata Temples', nameHi: 'सीता माता मंदिर', description: 'Sacred sites and shrines exclusively dedicated to Goddess Sita.', longDescription: 'Sita Mata Temples are sacred sites and shrines dedicated to Goddess Sita. These temples are connected with devotion, purity, courage, sacrifice, and important places from the Ramayana tradition.', deity: 'Rama', icon: '🏹', group: 'unique-deities-avatars', order: 13, isActive: true, relatedSlugs: ['ramayana-circuit', 'rama-kshetras'] },
  { slug: 'chitragupta-yama-temples', name: 'Chitragupta & Yama Temples', nameHi: 'चित्रगुप्त और यम मंदिर', description: 'Rare temples dedicated to the deities of karma, death, and cosmic justice.', longDescription: 'Chitragupta & Yama Temples are rare shrines dedicated to the deities of karma, death, and cosmic justice. These temples preserve traditions around moral accountability, ancestral rites, and the spiritual law of actions.', deity: 'Multi', icon: '⚖️', group: 'unique-deities-avatars', order: 14, isActive: true, relatedSlugs: ['temple-ghats', 'kumbh-mela-sites'] },

  // ── Regional, Cultural & Nature ──
  { slug: 'kuldevi-kuldevata-temples', name: 'Kuldevi & Kuldevata Temples', nameHi: 'कुलदेवी और कुलदेवता मंदिर', description: 'Temples of ancestral family deities, highly prominent in various states.', longDescription: 'Kuldevi & Kuldevata Temples are ancestral family deity shrines worshiped across communities and regions. These temples preserve lineage memory, clan identity, family vows, and deeply personal forms of devotion.', deity: 'Devi', icon: '👑', group: 'regional-cultural-nature', order: 1, isActive: true, relatedSlugs: ['grama-devata-temples', 'protection-temples'] },
  { slug: 'grama-devata-temples', name: 'Grama Devata Temples', nameHi: 'ग्राम देवता मंदिर', description: 'Highly revered guardian village deities worshiped across rural India.', longDescription: 'Grama Devata Temples are village guardian deity shrines worshiped across rural India. These temples protect settlements, fields, water sources, and community life through local traditions passed down over generations.', deity: 'Multi', icon: '🛖', group: 'regional-cultural-nature', order: 2, isActive: true, relatedSlugs: ['kuldevi-kuldevata-temples', 'protection-temples'] },
  { slug: 'desert-temple-circuit', name: 'Desert Temple Circuit', nameHi: 'मरुस्थल मंदिर सर्किट', description: 'Majestic ancient temples rising from arid landscapes and sand dunes.', longDescription: 'The Desert Temple Circuit brings together majestic ancient temples rising from arid landscapes, dunes, and desert settlements. These temples show how devotion, architecture, and sacred community life flourished in challenging environments.', deity: 'Multi', icon: '🏜️', group: 'regional-cultural-nature', order: 3, isActive: true, relatedSlugs: ['ancient-temple-kingdoms', 'temple-architecture-styles'] },
  { slug: 'coastal-sea-shore-temples', name: 'Coastal & Sea Shore Temples', nameHi: 'तटीय मंदिर', description: 'Historic temples built directly on the shores of the ocean.', longDescription: 'Coastal & Sea Shore Temples are historic shrines built beside the ocean and sacred coastlines. These temples combine maritime culture, pilgrimage, sunrise rituals, and powerful traditions of worship near the sea.', deity: 'Multi', icon: '🌊', group: 'regional-cultural-nature', order: 4, isActive: true, relatedSlugs: ['char-dham', 'parashurama-kshetras', 'island-temples'] },
  { slug: 'island-temples', name: 'Island Temples', nameHi: 'द्वीप मंदिर', description: 'Sacred shrines uniquely located on river islands or in the middle of the sea.', longDescription: 'Island Temples are sacred shrines uniquely located on river islands, lake islands, or in sea-surrounded locations. These temples create a special pilgrimage experience shaped by water, isolation, and sacred geography.', deity: 'Multi', icon: '🏝️', group: 'regional-cultural-nature', order: 5, isActive: true, relatedSlugs: ['coastal-sea-shore-temples', 'sacred-river-temples'] },
  { slug: 'vana-kshetras-forest-temples', name: 'Vana Kshetras / Forest Temples', nameHi: 'वन क्षेत्र मंदिर', description: 'Ancient and mysterious temples hidden deep within sacred forests.', longDescription: 'Vana Kshetras and Forest Temples are ancient shrines hidden within sacred groves and forest landscapes. These temples preserve a deep bond between nature, wildlife, local ecology, and devotional worship.', deity: 'Multi', icon: '🌳', group: 'regional-cultural-nature', order: 6, isActive: true, relatedSlugs: ['himalayan-temples', 'cave-temples'] },
  { slug: 'patal-subterranean-temples', name: 'Patal / Subterranean Temples', nameHi: 'पाताल मंदिर', description: 'Sacred shrines situated deep underground or inside natural subterranean caves.', longDescription: 'Patal / Subterranean Temples are sacred shrines situated underground, within deep chambers, or inside natural subterranean caves. They are often associated with mystery, meditation, hidden waters, and powerful earth energies.', deity: 'Multi', icon: '🕳️', group: 'regional-cultural-nature', order: 7, isActive: true, relatedSlugs: ['cave-temples', 'rock-cut-temples'] },
  { slug: 'parashurama-kshetras', name: 'Parashurama Kshetras', nameHi: 'परशुराम क्षेत्र', description: 'Sacred coastal lands and temples associated with Lord Parashurama.', longDescription: 'Parashurama Kshetras are sacred coastal lands and temples associated with Lord Parashurama, the warrior-sage avatar of Vishnu. These regions are especially connected with western coastal traditions, temple founding legends, and Brahmin settlements.', deity: 'Vishnu', icon: '🪓', group: 'regional-cultural-nature', order: 8, isActive: true, relatedSlugs: ['coastal-sea-shore-temples', 'kerala-temple-circuit'] },

  // ── Specialized Groups & Traditions ──
  { slug: 'ashta-veeratta-stalas', name: 'Ashta Veeratta Stalas', nameHi: 'अष्ट वीरट्टानम', description: 'Eight ancient temples in Tamil Nadu where Lord Shiva performed heroic deeds.', longDescription: 'Ashta Veeratta Stalas are eight ancient Shiva temples in Tamil Nadu where Lord Shiva is believed to have performed heroic deeds. These shrines preserve powerful Shaiva legends and are important to Tamil temple tradition.', deity: 'Shiva', icon: '⚔️', group: 'specialized-traditions', order: 1, isActive: true, relatedSlugs: ['108-shiva-temples', 'pancha-bhoota-stalam', 'chola-temples'] },
  { slug: 'sapta-vitanka-stalas', name: 'Sapta Vitanka Stalas', nameHi: 'सप्त विडंग स्थल', description: 'Seven special shrines featuring unique, naturally formed emerald Shiva lingams.', longDescription: 'Sapta Vitanka Stalas are seven special Shiva shrines associated with unique forms of Tyagaraja and sacred lingams. These temples are deeply connected with Tamil Shaiva worship, music, dance, and temple ritual traditions.', deity: 'Shiva', icon: '💎', group: 'specialized-traditions', order: 2, isActive: true, relatedSlugs: ['chola-temples', 'pancha-sabhai', '108-shiva-temples'] },
  { slug: 'chausath-yogini-temples', name: 'Chausath Yogini Temples', nameHi: 'चौसठ योगिनी मंदिर', description: 'Ancient, circular, open-air tantric temples of the 64 mystical Yoginis.', longDescription: 'Chausath Yogini Temples are ancient, circular, open-air tantric temples dedicated to the 64 Yoginis. These rare shrines are important for understanding Shakti worship, tantra, sacred geometry, and early temple architecture.', deity: 'Shakti', icon: '⭕', group: 'specialized-traditions', order: 3, isActive: true, relatedSlugs: ['tantra-peethas', 'dasha-mahavidya-temples', 'shakti-peeth'] },
  { slug: 'swaminarayan-temples', name: 'Swaminarayan Temples', nameHi: 'स्वामीनारायण मंदिर', description: 'Grand architectural masterpieces of the Swaminarayan tradition.', longDescription: 'Swaminarayan Temples are grand devotional and architectural centers of the Swaminarayan tradition. These temples emphasize disciplined devotion, community service, beautiful craftsmanship, and modern temple organization.', deity: 'Vishnu', icon: '🛕', group: 'specialized-traditions', order: 4, isActive: true, relatedSlugs: ['divya-desam', 'temple-architecture-styles'] },
  { slug: 'nakshatra-temples', name: 'Nakshatra Temples', nameHi: '27 नक्षत्र मंदिर', description: 'Twenty-seven specific temples associated with the 27 Vedic birth stars for astrological remedies.', longDescription: 'Nakshatra Temples are 27 sacred temples associated with the Vedic birth stars. Devotees visit these shrines for astrological remedies, spiritual balance, and blessings connected with their janma nakshatra.', deity: 'Multi', icon: '🌟', group: 'specialized-traditions', order: 5, isActive: true, relatedSlugs: ['navagraha', 'rashi-temples'] },
  { slug: 'rashi-temples', name: 'Rashi Temples', nameHi: '12 राशि मंदिर', description: 'Twelve sacred temples linked to the astrological Zodiac signs.', longDescription: 'Rashi Temples are sacred shrines associated with the twelve zodiac signs. They are visited for astrological balance, planetary remedies, and spiritual practices linked with birth sign traditions.', deity: 'Multi', icon: '♈', group: 'specialized-traditions', order: 6, isActive: true, relatedSlugs: ['navagraha', 'nakshatra-temples'] },
  { slug: 'kumbh-mela-sites', name: 'Kumbh Mela Sites', nameHi: 'कुंभ मेला स्थल', description: 'The four holiest river convergence cities hosting the grand Kumbh Mela.', longDescription: 'Kumbh Mela Sites are the four sacred cities associated with the grand Kumbh Mela: Prayagraj, Haridwar, Ujjain, and Nashik. These river pilgrimage centers are among the most important gathering places in Hindu spiritual life.', deity: 'Multi', icon: '🏺', group: 'specialized-traditions', order: 7, isActive: true, relatedSlugs: ['sapta-puri', 'sacred-river-temples', 'temple-ghats'] },
  { slug: 'ashta-lakshmi-temples', name: 'Ashta Lakshmi Temples', nameHi: 'अष्ट लक्ष्मी मंदिर', description: 'Eight sacred shrines dedicated to the eight divine forms of Goddess Lakshmi.', longDescription: 'Ashta Lakshmi Temples are dedicated to the eight divine forms of Goddess Lakshmi, representing prosperity, courage, wisdom, food, progeny, victory, wealth, and spiritual abundance.', deity: 'Lakshmi', icon: '🪷', group: 'specialized-traditions', order: 8, isActive: true, relatedSlugs: ['wealth-prosperity-temples', 'lalita-tripura-sundari-temples'] },
  { slug: 'panchayatana-temples', name: 'Panchayatana Temples', nameHi: 'पंचायतन मंदिर', description: 'Smarta tradition temples honoring a central deity surrounded by four other principal gods.', longDescription: 'Panchayatana Temples follow the Smarta tradition of worshiping a central deity surrounded by four other principal deities. These temples express the unity of Shiva, Vishnu, Devi, Surya, and Ganesha worship.', deity: 'Multi', icon: '🔥', group: 'specialized-traditions', order: 9, isActive: true, relatedSlugs: ['adi-shankaracharya-maths', 'harihara-temples'] },
  { slug: 'swayambhu-temples', name: 'Swayambhu Temples', nameHi: 'स्वयंभू मंदिर', description: 'Highly powerful shrines where the primary deity is believed to be self-manifested from the earth.', longDescription: 'Swayambhu Temples are powerful shrines where the primary deity is believed to be self-manifested. These temples hold special reverence because the murti or lingam is not considered man-made but revealed by divine presence.', deity: 'Multi', icon: '🌸', group: 'specialized-traditions', order: 10, isActive: true, relatedSlugs: ['jyotirlinga', 'siddha-peeths', 'cave-temples'] },
  { slug: 'jeeva-samadhi-temples', name: 'Jeeva Samadhi Temples', nameHi: 'जीव समाधि मंदिर', description: 'Shrines built over the final resting places of highly enlightened saints and Siddhas.', longDescription: 'Jeeva Samadhi Temples are shrines built over the final resting places of enlightened saints, Siddhas, and realized masters. These sites are revered as powerful meditation centers where the saintly presence continues to bless devotees.', deity: 'Multi', icon: '🙏', group: 'specialized-traditions', order: 11, isActive: true, relatedSlugs: ['saptarishi-ashrams', 'nath-sampradaya-temples'] },
  { slug: 'rath-yatra-temples', name: 'Rath Yatra Temples', nameHi: 'रथ यात्रा मंदिर', description: 'Temples famous for their massive, historic chariot festivals.', longDescription: 'Rath Yatra Temples are famous for massive and historic chariot festivals where deities are taken out for public darshan. These festivals bring together devotion, music, ritual, community service, and sacred celebration.', deity: 'Multi', icon: '🛞', group: 'specialized-traditions', order: 12, isActive: true, relatedSlugs: ['char-dham', 'temple-towns'] },

  // ── Other ──
  { slug: 'other-sacred-group', name: 'Other Sacred Group', nameHi: 'अन्य पवित्र समूह', description: 'Other sacred temple groups and circuits.', longDescription: 'Other sacred temple groupings that don\'t fit into the main categories above. These include regional pilgrimage circuits, lesser-known sacred clusters, and emerging spiritual destinations.', deity: 'Multi', icon: '🙏', group: 'other', order: 1, isActive: true, relatedSlugs: [] },
]

// ─── Indexes & Helpers ───────────────────────────────────────────────────────

const _bySlug = new Map<string, SacredCategory>()
const _byName = new Map<string, SacredCategory>()
for (const cat of SACRED_CATEGORIES) {
  _bySlug.set(cat.slug, cat)
  _byName.set(cat.name.toLowerCase(), cat)
}

// Backward-compatible slug aliases
_bySlug.set('shakti-peethas', _bySlug.get('shakti-peeth')!)
_bySlug.set('51-shakti-peethas', _bySlug.get('shakti-peeth')!)
_bySlug.set('52-shakti-peethas', _bySlug.get('shakti-peeth')!)

export function getCategoryBySlug(slug: string): SacredCategory | undefined {
  return _bySlug.get(slug)
}

export function getCategoryByName(name: string): SacredCategory | undefined {
  return _byName.get(name.toLowerCase())
}

export function getSlugForCategoryName(name: string): string {
  return getCategoryByName(name)?.slug || name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '')
}

export function getCategoryNameForSlug(slug: string): string {
  return getCategoryBySlug(slug)?.name || slug
}

export function getAllCategoryNames(): string[] {
  return SACRED_CATEGORIES.filter(c => c.isActive).map(c => c.name)
}

export function getAllCategorySlugs(): string[] {
  return SACRED_CATEGORIES.filter(c => c.isActive).map(c => c.slug)
}

export function getCategoriesByGroup(groupKey: string): SacredCategory[] {
  return SACRED_CATEGORIES.filter(c => c.group === groupKey && c.isActive).sort((a, b) => a.order - b.order)
}

export function getGroupedCategories(): { group: CategoryGroup; categories: SacredCategory[] }[] {
  return CATEGORY_GROUPS.map(group => ({
    group,
    categories: getCategoriesByGroup(group.key),
  })).filter(g => g.categories.length > 0)
}
