import Link from 'next/link'
import { notFound } from 'next/navigation'
import SarvdevImage from '@/components/SarvdevImage'
import ShareButtons from '@/components/ShareButtons'
import { getBlogHeroImage, getBlogCardImage } from '@/lib/temple-image'
import { formatBlogDate, getBlogContent, getBlogExcerpt } from '@/lib/blog-utils'
import { getPublishedStory, getRelatedStories, hasStoryMedia } from '@/lib/sacred-stories'

export default async function StoryPage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const story = await getPublishedStory(slug); if (!story) notFound()
  const related = await getRelatedStories(story); const content = getBlogContent(story); const url = `https://sarvdev.com/blog/${story.slug}`
  const schema = { '@context': 'https://schema.org', '@type': 'BlogPosting', headline: story.title, ...(story.excerpt && { description: story.excerpt }), ...(story.author && { author: { '@type': 'Person', name: story.author } }), ...(formatBlogDate(story) && { datePublished: new Date(story.publishedAt || story.date || story.createdAt).toISOString() }), mainEntityOfPage: url }
  return <article className="bg-surface pb-20"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} /><div className="page-container max-w-4xl py-10 sm:py-14"><nav className="text-sm text-ink-muted"><Link href="/" className="underline">Home</Link><span> / </span><Link href="/blog" className="underline">Sacred Stories</Link><span> / </span><span>{story.title}</span></nav><header className="mt-10 max-w-3xl">{story.category && <p className="text-overline font-semibold uppercase tracking-[.18em] text-primary-700">{story.category}</p>}<h1 className="mt-3 font-serif text-4xl leading-tight text-ink sm:text-6xl">{story.title}</h1>{story.titleHi && <p className="mt-3 font-devanagari text-2xl text-ink-muted">{story.titleHi}</p>}<div className="mt-5 flex flex-wrap gap-x-4 gap-y-2 text-sm text-ink-muted">{formatBlogDate(story) && <span>{formatBlogDate(story)}</span>}{story.author && <span>By {story.author}</span>}</div></header>{hasStoryMedia(story) && <div className="relative mt-10 aspect-[16/9] overflow-hidden bg-surface-sunken"><SarvdevImage image={getBlogHeroImage(story)} alt={story.title} className="absolute inset-0" imgClassName="object-cover" loading="eager" /></div>}<div className="mt-8 flex justify-end"><ShareButtons title={story.title} url={url} /></div><div className="mx-auto max-w-3xl"><div className="font-serif text-lg leading-9 text-ink whitespace-pre-wrap">{content || story.excerpt || ''}</div></div>{related.length > 0 && <section className="mt-16 border-t border-surface-border pt-8"><p className="text-overline font-semibold uppercase tracking-[.18em] text-primary-700">Continue reading</p><h2 className="mt-2 font-serif text-3xl text-ink">Related Sacred Stories</h2><div className="mt-6 grid gap-6 sm:grid-cols-2">{related.map((item) => <Link key={String(item._id)} href={`/blog/${item.slug}`} className="border-t border-surface-border pt-3 no-underline">{hasStoryMedia(item) && <div className="relative mb-4 aspect-video overflow-hidden"><SarvdevImage image={getBlogCardImage(item)} alt={item.title} className="absolute inset-0" imgClassName="object-cover" /></div>}<p className="font-serif text-2xl text-ink">{item.title}</p>{item.excerpt && <p className="mt-2 text-sm text-ink-muted">{item.excerpt}</p>}</Link>)}</div></section>}</div></article>
}
