// models/Darshan.ts
import mongoose, { Schema, models } from 'mongoose';

const DarshanSchema = new Schema({
  title: { type: String, required: true },
  titleHi: { type: String },
  description: { type: String },
  descriptionHi: { type: String },
  temple: { type: String },
  templeName: { type: String },
  templeNameHi: { type: String },
  deity: { type: String },
  deityHi: { type: String },
  location: { type: String },
  city: { type: String },
  state: { type: String },
  media: { type: String },
  thumbnail: { type: String },
  image: { type: String },
  imageCard: { type: String },
  imageHero: { type: String },
  time: { type: String },
  date: { type: String },
  schedule: { type: String },
  darshanDate: { type: String },
  startTime: { type: String },
  endTime: { type: String },
  repeatDays: [{ type: String }],
  timezone: { type: String, default: 'Asia/Kolkata' },
  festivalTag: { type: String },
  video: { type: String },
  videoUrl: { type: String },
  youtubeUrl: { type: String },
  youtubeId: { type: String },
  isLive: { type: Boolean, default: false },
  darshanType: { type: String, enum: ['live', 'recorded', 'upcoming'], default: 'recorded' },
  type: { type: String, enum: ['live', 'recorded', 'upcoming'], default: 'recorded' },
  priority: { type: Number, default: 999 },
  featured: { type: Boolean, default: false },
  isFeatured: { type: Boolean, default: false },
  templeSlug: { type: String },
  deitySlug: { type: String },
  relatedDevotionalSlug: { type: String },
  externalUrl: { type: String },
  metaTitle: { type: String },
  metaDescription: { type: String },
  ogImage: { type: String },
  status: { type: String, enum: ['active', 'inactive', 'draft', 'approved', 'pending', 'rejected'], default: 'draft' },
  createdAt: { type: Date, default: Date.now }
});

export default models.Darshan || mongoose.model('Darshan', DarshanSchema);
